### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tonymai** [jannypie/jannypie.github.io#1]
Nice vibrant colors on your site. It's very eye-catching! There's one thing that confused me a little bit. The Introduction link brings me down to the bottom of the page, but since the intro paragraph starts midway through the view of the bottom page, I had to look around for a little bit before I actually found it. This might confused others as well. Can't wait to see it after you develop it some more!

**Comment by jannypie** [comment]
Thanks for the feedback, I have moved the intro section further up on the page so it doesn't do that! I appreciate the callout!
